#!/bin/bash
# IMPORTANT!: There is a discrepancy between DOS and UNIX carriage return (\r). This script must be UNIX encoded. e.g. Notepad++: Edit>EOL Conversion>Unix (LF)

echo "*****************************"
echo "** YOU ARE INSIDE: exec.sh"
echo "** USER: " $(whoami)
echo "** PWD: " $(pwd)
echo "** LS: " $(ls)
echo "** GPU AVAILABLE: " $(python3 -c 'import torch; print(torch.cuda.is_available())')
echo "*****************************"

# EXECUTE WHATEVER YOU WISH
export EXTERNALIP=$(curl http://ifconfig.me/ip)
echo "*****************************"
echo "** THE EXTERNAL IP I FOUND AND USE IS " $EXTERNALIP
echo "*****************************" 
cd code
# uvicorn --ssl-keyfile server.key --ssl-certfile server.pem main:app --host 0.0.0.0 --port 5035
uvicorn main:app --host 0.0.0.0 --port 5035


# PREVENT DOCKER FROM EXITING
tail -f /dev/null
